"""
Site Graph Visualizer — Interactive HTML visualization of crawled site structure.

Generates a self-contained HTML file with a force-directed graph showing:
- Pages as nodes (sized by word count)
- Internal links as edges
- Color by HTTP status (green=200, orange=301, red=4xx/5xx)
- Depth layers
- Orphan page detection
"""

import json
import time
from typing import Optional


def generate_site_graph(pages: list[dict], title: str = "Site Graph") -> str:
    """
    Generate interactive HTML site graph from crawled pages.

    Args:
        pages: List of CrawledPage.to_dict() results
        title: Graph title

    Returns:
        Complete HTML string with embedded D3.js visualization
    """
    # Build nodes and edges
    nodes = []
    edges = []
    url_to_idx = {}

    for i, page in enumerate(pages):
        url = page.get("url", "")
        url_to_idx[url] = i
        nodes.append({
            "id": i,
            "url": url,
            "label": _short_url(url),
            "title": page.get("title", ""),
            "status": page.get("http_status", 0),
            "depth": page.get("depth", 0),
            "words": page.get("word_count", 0),
            "duplicate": page.get("is_duplicate", False),
        })

    # Build edges from internal links (simplified — we track parent→child from depth)
    for i, page in enumerate(pages):
        depth = page.get("depth", 0)
        # Connect to pages at depth-1 (approximate parent)
        if depth > 0:
            for j, other in enumerate(pages):
                if other.get("depth", 0) == depth - 1 and j != i:
                    edges.append({"source": j, "target": i})
                    break  # One parent per node for cleaner graph

    timestamp = time.strftime("%Y-%m-%d %H:%M")
    nodes_json = json.dumps(nodes)
    edges_json = json.dumps(edges)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; background:#0f172a; color:#e2e8f0; overflow:hidden; }}
#graph {{ width:100vw; height:100vh; }}
.info {{ position:fixed; top:16px; left:16px; background:rgba(15,23,42,0.95); border:1px solid #334155; border-radius:8px; padding:16px; max-width:320px; z-index:10; }}
.info h1 {{ font-size:1rem; color:#38bdf8; margin-bottom:8px; }}
.info p {{ font-size:0.75rem; color:#94a3b8; line-height:1.5; }}
.stats {{ display:grid; grid-template-columns:1fr 1fr; gap:8px; margin-top:12px; }}
.stats .s {{ text-align:center; background:#1e293b; border-radius:4px; padding:8px; }}
.stats .s .n {{ font-size:1.2rem; font-weight:700; color:#38bdf8; }}
.stats .s .l {{ font-size:0.65rem; color:#64748b; }}
.legend {{ position:fixed; bottom:16px; left:16px; background:rgba(15,23,42,0.95); border:1px solid #334155; border-radius:8px; padding:12px; font-size:0.7rem; }}
.legend span {{ display:inline-block; width:10px; height:10px; border-radius:50%; margin-right:4px; vertical-align:middle; }}
.tooltip {{ position:fixed; background:#1e293b; border:1px solid #475569; border-radius:6px; padding:8px 12px; font-size:0.75rem; pointer-events:none; display:none; z-index:100; max-width:400px; }}
svg circle {{ cursor:pointer; transition:r 0.2s; }}
svg circle:hover {{ filter:brightness(1.3); }}
svg line {{ stroke-opacity:0.3; }}
</style>
</head>
<body>
<div class="info">
    <h1>🔗 {title}</h1>
    <p>Generated by ySEO-PRO-AI • {timestamp}</p>
    <div class="stats">
        <div class="s"><div class="n">{len(nodes)}</div><div class="l">Pages</div></div>
        <div class="s"><div class="n">{len(edges)}</div><div class="l">Links</div></div>
        <div class="s"><div class="n">{sum(1 for n in nodes if n['status']==200)}</div><div class="l">OK (200)</div></div>
        <div class="s"><div class="n">{sum(1 for n in nodes if n['status']>=400)}</div><div class="l">Errors</div></div>
    </div>
</div>
<div class="legend">
    <span style="background:#22c55e"></span> 200 OK
    <span style="background:#f59e0b;margin-left:8px"></span> Redirect
    <span style="background:#ef4444;margin-left:8px"></span> Error
    <span style="background:#8b5cf6;margin-left:8px"></span> Duplicate
</div>
<div class="tooltip" id="tip"></div>
<svg id="graph"></svg>

<script>
const nodes = {nodes_json};
const edges = {edges_json};

const svg = document.getElementById('graph');
const width = window.innerWidth;
const height = window.innerHeight;
svg.setAttribute('width', width);
svg.setAttribute('height', height);

// Color by status
function nodeColor(n) {{
    if (n.duplicate) return '#8b5cf6';
    if (n.status >= 400) return '#ef4444';
    if (n.status >= 300) return '#f59e0b';
    return '#22c55e';
}}

// Size by word count
function nodeSize(n) {{
    return Math.max(4, Math.min(20, Math.sqrt(n.words || 100) / 2));
}}

// Simple force simulation
const positions = nodes.map((n, i) => ({{
    x: width/2 + (Math.random()-0.5) * 400 + n.depth * 80,
    y: height/2 + (Math.random()-0.5) * 400,
    vx: 0, vy: 0,
}}));

// Draw edges
edges.forEach(e => {{
    const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
    line.id = `e${{e.source}}-${{e.target}}`;
    line.setAttribute('stroke', '#475569');
    line.setAttribute('stroke-width', '1');
    svg.appendChild(line);
}});

// Draw nodes
nodes.forEach((n, i) => {{
    const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
    circle.setAttribute('r', nodeSize(n));
    circle.setAttribute('fill', nodeColor(n));
    circle.id = `n${{i}}`;
    circle.addEventListener('mouseenter', (e) => {{
        const tip = document.getElementById('tip');
        tip.innerHTML = `<strong>${{n.label}}</strong><br>${{n.title || '(no title)'}}<br>Status: ${{n.status}} | Words: ${{n.words}} | Depth: ${{n.depth}}`;
        tip.style.display = 'block';
        tip.style.left = (e.clientX + 12) + 'px';
        tip.style.top = (e.clientY - 30) + 'px';
    }});
    circle.addEventListener('mouseleave', () => {{
        document.getElementById('tip').style.display = 'none';
    }});
    svg.appendChild(circle);
}});

// Simple force layout (60 iterations)
for (let iter = 0; iter < 60; iter++) {{
    // Repulsion
    for (let i = 0; i < nodes.length; i++) {{
        for (let j = i+1; j < nodes.length; j++) {{
            let dx = positions[i].x - positions[j].x;
            let dy = positions[i].y - positions[j].y;
            let d = Math.sqrt(dx*dx + dy*dy) || 1;
            let force = 5000 / (d * d);
            positions[i].vx += dx/d * force;
            positions[i].vy += dy/d * force;
            positions[j].vx -= dx/d * force;
            positions[j].vy -= dy/d * force;
        }}
    }}
    // Attraction (edges)
    edges.forEach(e => {{
        let dx = positions[e.target].x - positions[e.source].x;
        let dy = positions[e.target].y - positions[e.source].y;
        let d = Math.sqrt(dx*dx + dy*dy) || 1;
        let force = d * 0.01;
        positions[e.source].vx += dx/d * force;
        positions[e.source].vy += dy/d * force;
        positions[e.target].vx -= dx/d * force;
        positions[e.target].vy -= dy/d * force;
    }});
    // Center gravity
    positions.forEach(p => {{
        p.vx += (width/2 - p.x) * 0.001;
        p.vy += (height/2 - p.y) * 0.001;
        p.x += p.vx * 0.3;
        p.y += p.vy * 0.3;
        p.vx *= 0.7;
        p.vy *= 0.7;
        p.x = Math.max(20, Math.min(width-20, p.x));
        p.y = Math.max(20, Math.min(height-20, p.y));
    }});
}}

// Update positions
nodes.forEach((n, i) => {{
    document.getElementById(`n${{i}}`).setAttribute('cx', positions[i].x);
    document.getElementById(`n${{i}}`).setAttribute('cy', positions[i].y);
}});
edges.forEach(e => {{
    const line = document.getElementById(`e${{e.source}}-${{e.target}}`);
    line.setAttribute('x1', positions[e.source].x);
    line.setAttribute('y1', positions[e.source].y);
    line.setAttribute('x2', positions[e.target].x);
    line.setAttribute('y2', positions[e.target].y);
}});
</script>
</body>
</html>"""

    return html


def save_site_graph(html: str, output_path: str = "") -> str:
    """Save site graph HTML to file."""
    import os
    if not output_path:
        os.makedirs("reports", exist_ok=True)
        ts = time.strftime("%Y%m%d-%H%M%S")
        output_path = f"reports/sitegraph-{ts}.html"
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    return output_path


def _short_url(url: str) -> str:
    """Shorten URL for display."""
    from urllib.parse import urlparse
    parsed = urlparse(url)
    path = parsed.path or "/"
    if len(path) > 40:
        path = path[:37] + "..."
    return path
